// ─── MODE LIAR ───────────────────────────────────────────────────
// Vibe: eksplisit, vulgar, langsung, no-filter — khusus 17+
// Ratio: lebih banyak DARE (aksi) daripada TRUTH (pertanyaan)
// {AKU} = pemain giliran ini · {KAMU} = pasangannya

window.CHALLENGES_LIAR = {

  truth: {
    mild: [
      "Bagian tubuh {KAMU} mana yang paling ingin {AKU} jilat malam ini — dan {AKU} mau mulai dari mana?",
      "Apa yang paling membuat {AKU} basah atau terangsang dari {KAMU} — suara, gerakan, atau sentuhan apa?",
      "Di mana tepatnya di tubuh {AKU} yang paling ingin {AKU} rasakan mulut {KAMU} sekarang?",
      "Kata-kata apa dari mulut {KAMU} yang paling bisa langsung membuat {AKU} tidak bisa berpikir jernih?",
      "Saat {AKU} hampir klimaks, {AKU} lebih suka {KAMU} mempercepat, memperlambat, atau menekan lebih keras?",
      "Apa yang {AKU} lakukan dengan tangan {AKU} sendiri saat kalian sedang intim berdua?",
    ],
    medium: [
      "Posisi atau gaya bersetubuh yang belum pernah kalian coba tapi sudah lama {AKU} bayangkan — ceritakan detailnya.",
      "Kalau {AKU} bisa memerintahkan {KAMU} satu hal ke tubuh {AKU} malam ini tanpa ditolak — apa perintahnya?",
      "Apa gaya yang membuat {AKU} merasa paling penuh dan paling memuaskan — ceritakan posisinya.",
      "Seberapa dalam {AKU} suka {KAMU} masuk saat melakukan oral — tunjukkan seberapa dalam batasnya sekarang.",
      "Di mana lokasi di luar kamar yang paling ingin {AKU} jadikan tempat Bersetubuh dengan {KAMU}?",
      "Ceritakan momen paling eksplisit antara {AKU} dan {KAMU} yang paling tidak bisa {AKU} lupakan.",
    ],
    hot: [
      "Di mana tepatnya {AKU} mau {KAMU} akhiri saat Bersetubuh — di dalam, di luar, atau di bagian tubuh mana?",
      "Kalau malam ini tidak ada batasan sama sekali, apa 3 hal pertama yang ingin {AKU} lakukan ke {KAMU}?",
      "Apa kata-kata paling kotor yang ingin {AKU} dengar {KAMU} ucapkan tepat di telinga {AKU} saat klimaks?",
      "Gerakan tangan {KAMU} seperti apa yang paling {AKU} suka — tunjukkan langsung ke tangan {KAMU} di tubuh {AKU}.",
      "Kalau {AKU} minta {KAMU} melakukan apapun ke tubuh {AKU} malam ini tanpa boleh menolak — apa 3 hal pertama?",
      "Saat kita melakukan 69, {AKU} lebih fokus menikmati atau memberi — dan kenapa?",
    ],
  },

  dare: {
    mild: [
      "{AKU} bisikkan ke {KAMU} dengan sangat detail — bagian tubuh {KAMU} yang paling ingin {AKU} jilat malam ini dan caranya — lakukan selama 30 detik.",
      "{AKU} tunjuk langsung bagian tubuh {AKU} yang paling sensitif, lalu katakan ke {KAMU}: 'Aku mau kamu ___ di sini.' Isi titiknya — lakukan selama 20 detik.",
      "{AKU} ucapkan keras-keras tanpa senyum dan tanpa malu sambil tatap mata {KAMU}: 'Aku mau kamu ___ aku malam ini.' Isi titiknya — lakukan selama 20 detik.",
      "{AKU} tunjuk bagian tubuh {KAMU} lalu bilang: 'Aku mau kamu pakai ini untuk ___.' Lengkapi kalimatnya dengan jujur — lakukan selama 30 detik.",
      "{AKU} sebutkan tiga bagian tubuh {KAMU} yang paling membuat {AKU} terangsang — satu per satu, dengan penjelasan kenapa — lakukan selama 30 detik.",
      "{AKU} bisikkan instruksi spesifik ke telinga {KAMU}: persis apa yang {AKU} mau {KAMU} lakukan ke tubuh {AKU} sekarang — lakukan selama 30 detik.",
      "{AKU} kirim voice note ke HP {KAMU} sekarang — rekam suara {AKU} seperti biasa keluar di momen paling intim — lakukan selama 30 detik.",
      "{AKU} tunjukkan dengan tangan {AKU} sendiri di tubuh {AKU} — bagian mana dan gerakan yang {AKU} mau {KAMU} lakukan — lakukan selama 30 detik.",
      "{AKU} berlutut di depan {KAMU}, tatap matanya dari bawah, dan ucapkan dengan detail apa yang ingin {AKU} lakukan malam ini — lakukan selama 20 detik.",
      "{AKU} berdiri di depan {KAMU}, buka bagian atas baju {AKU} sendiri perlahan — tatap mata {KAMU} sepanjang waktu — lakukan selama 20 detik.",
      "{AKU} gambarkan ke {KAMU} dengan kata-kata paling vulgar yang bisa {AKU} keluarkan, apa yang ingin {AKU} rasakan malam ini — lakukan selama 30 detik.",
      "{AKU} minta {KAMU} berdiri diam — {AKU} punya 30 detik untuk menyentuh bagian tubuh {KAMU} yang paling {AKU} inginkan.",
      "{AKU} usapkan jari {AKU} perlahan dari leher {KAMU} turun ke dada — terus turun sampai ke pinggang {KAMU} tanpa berhenti — lakukan selama 30 detik.",
      "{AKU} cium leher {KAMU} tepat 3 kali di titik yang sama — tiap kali makin dalam dan makin lama — lakukan selama 20 detik.",
      "{AKU} minta {KAMU} memejamkan mata — {AKU} sentuh bagian tubuh {KAMU} yang paling {AKU} inginkan selama 30 detik.",
      "{AKU} tulis nama {AKU} di tubuh {KAMU} menggunakan lidah {AKU} — pilih sendiri bagian tubuhnya — lakukan selama 30 detik.",
      "{AKU} pegang tangan {KAMU} dan taruh di bagian tubuh {AKU} yang paling sensitif — instruksikan cara yang {AKU} suka — lakukan selama 30 detik.",
      "{AKU} berdiri di belakang {KAMU}, tempel tubuh {AKU} ke tubuh {KAMU}, dan bisikkan hal paling vulgar yang ada di kepala {AKU} — lakukan selama 30 detik.",
      "{AKU} cium bibir {KAMU} selama 15 detik — tidak boleh berhenti, tidak boleh bersuara, tidak boleh senyum.",
      "{AKU} lepas pakaian dalam {AKU} sendiri tanpa melepas pakaian luar, serahkan ke {KAMU} sambil tatap matanya — lakukan selama 45 detik.",
    ],
    medium: [
      "{AKU} pandu tangan {KAMU} ke titik paling sensitif di tubuh {AKU} — tahan di sana, instruksikan cara dan tekanan yang {AKU} mau — lakukan selama 30 detik.",
      "{AKU} cium leher {KAMU} dari bawah telinga turun ke tulang selangka selama 20 detik — pakai lidah, tidak boleh berhenti.",
      "{AKU} lepas satu pakaian {AKU} perlahan di depan {KAMU} sambil mendeskripsikan apa yang {AKU} rasakan setiap detiknya — lakukan selama 45 detik.",
      "{AKU} pejamkan mata {KAMU} — sentuh 4 titik berbeda di tubuh {KAMU}. {KAMU} tebak semuanya. Salah = {AKU} ulangi lebih perlahan — lakukan selama 30 detik.",
      "{AKU} berbaring di samping {KAMU} — {AKU} punya 60 detik untuk menyentuh {KAMU} di mana dan bagaimana saja yang {AKU} mau.",
      "{AKU} cium paha dalam {KAMU} dari lutut naik ke atas — kanan dulu lalu kiri, tahan 5 detik di tiap titik.",
      "{AKU} gigit pelan leher {KAMU} lalu langsung cium bekasnya — ulangi 3 kali di titik yang berbeda-beda — lakukan selama 20 detik.",
      "{AKU} minta {KAMU} duduk diam — sentuh, remas, dan cium 3 bagian tubuh {KAMU} yang {AKU} pilih, 15 detik per bagian.",
      "{AKU} buka pakaian {KAMU} dari belakang perlahan — cium setiap bagian baru yang terbuka sebelum lanjut — lakukan selama 20 detik.",
      "{AKU} duduk di pangkuan {KAMU} menghadap ke depan, gerakkan pinggul {AKU} perlahan selama 90 detik — {KAMU} tidak boleh pegang {AKU} dulu.",
      "{AKU} rebahkan {KAMU}, pejamkan matanya, lalu cium dan sentuh tubuhnya dari leher turun ke perut selama 2 menit.",
      "{AKU} berdiri menghadap dinding, kedua tangan menempel dinding — biarkan {KAMU} berdiri di belakang {AKU} selama 3 menit melakukan apapun.",
      "{AKU} lepas bra atau pakaian dalam atas {KAMU} hanya dengan satu tangan dari belakang — cium bahu {KAMU} yang baru terbuka — lakukan selama 20 detik.",
      "{AKU} pegang pinggul {KAMU} dari belakang dan bisikkan dengan detail apa yang {AKU} bayangkan terjadi malam ini — lakukan selama 30 detik.",
      "{AKU} cium {KAMU} dari tulang selangka turun ke perut — tidak boleh skip satu bagian pun — lakukan selama 30 detik.",
      "{AKU} biarkan {KAMU} menutup mata {AKU} dengan kain — tebak 4 bagian tubuh {KAMU} yang disentuhkan ke kulit {AKU} — lakukan selama 30 detik.",
      "{AKU} ambil tangan {KAMU}, masukkan ke dalam baju {AKU} sendiri, dan jangan keluarkan selama 3 menit penuh.",
      "{AKU} tunjukkan ke {KAMU} ekspresi wajah persis yang muncul saat {AKU} di puncak — tahan 10 detik penuh tanpa malu.",
      "{AKU} lepas semua pakaian {AKU} sendiri perlahan di depan {KAMU} — {KAMU} duduk diam, tidak boleh menyentuh sampai {AKU} selesai — lakukan selama 2 menit.",
    ],
    hot: [
      "{AKU} cium {KAMU} mulai dari bibir turun ke leher, dada, perut, sampai ke batas celana dalam {KAMU} — tidak boleh angkat kepala — lakukan selama 30 detik.",
      "{AKU} lepas semua pakaian {KAMU} perlahan dengan tangan {AKU} — setiap item lepas, {AKU} cium bagian yang baru terbuka — lakukan selama 2 menit.",
      "{AKU} berbaring di tepi ranjang, kaki menjuntai ke bawah — biarkan {KAMU} berdiri dan lakukan apapun yang {KAMU} mau 3 menit.",
      "{AKU} tahan napas selama yang {AKU} bisa saat {KAMU} menstimulasi area sensitif {AKU} — kalau napas keluar, tantangan selesai.",
      "{AKU} tunjukkan ke {KAMU} cara persis yang paling {AKU} suka — pandu tangannya di tubuh {AKU}, instruksikan tiap detail — lakukan selama 30 detik.",
      "{AKU} lakukan oral pada {KAMU} sambil {KAMU} berdiri — berlutut di depan {KAMU}, jangan berhenti sampai {KAMU} bilang stop.",
      "{AKU} serahkan kontrol sepenuhnya ke {KAMU} selama 10 menit — tidak boleh meminta, mengarahkan, atau bergerak aktif.",
      "{AKU} berbaring dan biarkan {KAMU} mengikat mata {AKU} — {AKU} tebak 5 bagian tubuh {KAMU} yang disentuhkan ke kulit {AKU} — lakukan selama 30 detik.",
      "{AKU} lakukan oral pada {KAMU} selama 3 menit penuh tanpa boleh menggunakan tangan — hanya mulut {AKU} saja.",
      "{AKU} biarkan {KAMU} mengikat kedua tangan {AKU} ke kepala ranjang selama 5 menit — {AKU} tidak boleh bergerak sama sekali.",
      "{AKU} ambil tangan {KAMU}, letakkan tepat di bagian tubuh {AKU} yang paling sensitif — tunjukkan gerakan yang {AKU} inginkan — lakukan selama 30 detik.",
      "{AKU} berbisik langsung ke telinga {KAMU} selama 45 detik non-stop — ceritakan sedetail mungkin apa yang {AKU} ingin lakukan.",
      "{AKU} cium paha dalam {KAMU} naik turun selama 45 detik non-stop — sambil tangan {AKU} pegang pinggang {KAMU}.",
      "{AKU} rebahkan {KAMU} dan cium 5 titik berbeda di tubuh {KAMU} yang {AKU} pilih sendiri selama 75 detik — tahan 15 detik di tiap titik.",
      "{AKU} biarkan {KAMU} merekam video pendek tubuh {AKU} dalam pose yang {KAMU} pilih — {AKU} tidak boleh menolak posnya — lakukan selama 30 detik.",
      "{AKU} tunjukkan secara demonstrasi tanpa malu — gerakan pinggul yang paling nikmat saat {AKU} di posisi atas — lakukan selama 30 detik.",
      "{AKU} sebutkan satu hal yang kamu suka ke {KAMU} — dan lakukan sekarang juga selama 1 menit.",
      "{AKU} teteskan es batu dari leher {KAMU} turun ke perut — lalu bersihkan semuanya dengan lidah {AKU} perlahan selama 2 menit.",
      "{AKU} duduk di atas {KAMU} menghadap depan, gerakkan pinggul {AKU} perlahan — {KAMU} tidak boleh pegang {AKU} selama 90 detik.",
      "{AKU} cium paha dalam {KAMU} sambil tangan {AKU} terus bergerak bebas — jangan berhenti sampai {KAMU} bilang cukup.",
      "{AKU} minta {KAMU} berbaring — {AKU} duduk di atasnya menghadap ke kaki {KAMU} dan lakukan oral selama 3 menit penuh.",
      "{AKU} kenakan pakaian dalam {KAMU} — bukan punya {AKU} sendiri — dan jalan keliling kamar selama 2 menit.",
      "{AKU} lakukan lap dance untuk {KAMU} selama 3 menit — sambil menari {AKU} harus lepas minimal 2 item pakaian.",
      "{AKU} berbaring telentang — biarkan {KAMU} duduk di atas wajah {AKU} selama yang {KAMU} mau, {AKU} tidak boleh berhenti.",
      "{AKU} pegang kepala {KAMU} perlahan dan arahkan ke bagian tubuh {AKU} yang paling ingin {AKU} rasakan mulutnya — tanpa kata-kata.",
    ],
  },

  duo: [
    "Saling berciuman selama 2 menit tanpa berhenti — kedua tangan harus aktif bergerak di tubuh pasangan.",
    "Bergantian cium paha dalam pasangan 40 Detik — dari lutut naik ke atas, masing-masing 20 detik. Yang dicium tutup mata.",
    "Saling lepas semua pakaian satu sama lain — yang paling cepat selesai dapat kontrol penuh ke yang kalah selama 2 menit .",
    "Satu orang berbaring, yang lain punya 60 detik untuk menyentuh dan mencium sesukanya. Setelah itu ganti peran.",
    "Bergantian bisikkan instruksi vulgar ke telinga pasangan selama 60 detik — masing-masing harus langsung lakukan selama 30 detik.",
    "Tantangan 3 menit: 1 menit saling cium, 1 menit saling lepas pakaian, 1 menit terakhir bebas.",
    "Satu orang pejamkan mata — yang lain sentuh 5 titik berbeda. Yang ditutup mata tebak semua. Salah = lepas 1 pakaian.",
    "Saling pilihkan 1 titik di tubuh pasangan yang ingin disentuh — sentuh bersamaan selama 45 detik.",
    "Bergantian ucapkan kalimat ini sambil tatap mata pasangan: 'Malam ini aku mau kamu ___.' Pasangan langsung lakukan.",
    "Bergantian lakukan oral satu sama lain — masing-masing 2 menit, tidak boleh berhenti di tengah.",
    "Satu orang berbaring telentang — yang lain naik di atasnya dan lakukan sesukanya selama 3 menit. Setelah itu ganti posisi.",
    "Saling mengikat mata satu sama lain bergantian — yang dibutakan harus menebak apa yang pasangan lakukan ke tubuhnya.",
    "Tantangan 5 menit bebas — tidak ada aturan, tidak ada batas, lakukan apapun yang keduanya mau.",
    "Bergantian minta satu posisi atau gaya yang belum pernah dicoba — pasangan harus langsung setuju dan lakukan sekarang.",
    "Saling pijat titik paling sensitif satu sama lain secara bersamaan selama 2 menit — tidak boleh berhenti duluan.",
  ],

  berani: [
    "{AKU} cium {KAMU} mulai dari bibir turun ke leher, dada, perut, dan terus turun sampai ke batas celana dalam — tidak boleh angkat kepala.",
    "{AKU} lepas semua pakaian {KAMU} perlahan — setiap item lepas, {AKU} cium bagian yang baru terbuka selama 10 detik.",
    "{AKU} biarkan {KAMU} mengikat kedua tangan {AKU} ke kepala ranjang selama 5 menit — {KAMU} Lakukan sesukanya {AKU} tidak boleh bergerak sama sekali.",
    "{AKU} lakukan oral pada {KAMU} selama 5 menit — {KAMU} tidak boleh menggerakkan pinggul atau memegang kepala {AKU}.",
    "{AKU} serahkan kontrol sepenuhnya ke {KAMU} selama 10 menit — {AKU} tidak boleh meminta apapun.",
    "{AKU} tahan napas selama yang bisa saat {KAMU} menstimulasi area sensitif {AKU} — napas keluar, tantangan selesai.",
    "{AKU} Tunjukkan bagian tubuh {AKU} yang paling seduktif menurut {KAMU} dan biarkan {KAMU} merekamnya dari sudut yang {KAMU} pilih Selama 30 detik.",
    "{AKU} berbaring dan biarkan {KAMU} menutup mata {AKU} — tebak 5 bagian tubuh {KAMU} yang disentuhkan ke kulit {AKU}.",
    "{AKU} sebutkan satu hal yang belum pernah kita lakukan sama sekali — dan lakukan sekarang juga.",
    "{AKU} minta {KAMU} berbaring — {AKU} lakukan apapun yang {AKU} mau ke seluruh tubuh {KAMU} selama 10 menit penuh tanpa {KAMU} boleh bergerak aktif.",
    "{AKU} biarkan {KAMU} menentukan posisi tubuh {AKU} sesukanya — {AKU} tidak boleh bergerak dari posisi itu selama {KAMU} melakukan apapun.",
    "{AKU} lakukan oral pada {KAMU} sambil {KAMU} menonton video atau bermain HP — {AKU} tidak boleh berhenti sampai {KAMU} tidak bisa fokus lagi.",
    "{AKU} tantang {KAMU} — siapa yang bisa bertahan paling lama tanpa bersuara saat pasangan menstimulasi titik paling sensitifnya. Yang kalah menuruti 1 permintaan.",
    "{AKU} biarkan {KAMU} memotret atau merekam apapun yang {KAMU} mau selama 2 menit — {AKU} tidak boleh menolak pose atau instruksi apapun.",
    "{AKU} serahkan tubuh {AKU} sepenuhnya ke {KAMU} selama 15 menit — {AKU} tidak boleh bicara, meminta, atau menolak apapun yang {KAMU} lakukan.",
  ],

};